title: Giovanni Bonato
logo: images/Profile.png
description: Personal Portfolio
show_downloads: true

#IT SKILLS
#Microsoft Office (Excel, Word, Power Point)
#BI tools (Power BI, Tableau, SQL basics)
#Programming (R Studio, Python, Matlab)

#Languages
#Italian: Native speaker
#English: Level C1 (Advanced) - IELTS Academic certificate
#Spanish: Upper Intermediate

theme: jekyll-theme-minimal
